# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "chef/ubuntu-14.10"
  
  # Provision by shell
  config.vm.provision "shell",  path: "provision.sh"
  
   # Networking setting
  config.vm.network "forwarded_port", guest: 80, host: 8000 # subversion
  config.vm.network "forwarded_port", guest: 8081, host: 8001 # nexus

  # set an unique machine name
  config.vm.define :conditusTestEnv do |t|
  end

  config.vm.hostname = "conditusTestEnv"
  
end
